# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/clojure:boot-2.7.2-browsers

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      BOOT_JVM_OPTIONS: -Xmx3g -client -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xverify:none

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.boot" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: boot test-cljs -x
      - run: boot test

      - save_cache:
          paths:
            - "~/bin"
            - "~/.m2"
            - "~/.boot/cache/bin"
            - "~/.boot/cache/lib"
          key: v1-dependencies-{{ checksum "build.boot" }}

workflows:
  version: 2
  test:
    jobs:
      - test
